version: '3'

services:
  whoami0:
    image: emilevauge/whoami
    networks: 
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: 'Host: whoami0.freelyformd.com'
        traefik.port: 80

  whoami1:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: 'Host: whoami1.freelyformd.com'
        traefik.port: 80
        traefik.backend.loadbalancer.sticky: "true"


networks:
  proxy:
    external: true
