version: '3'

services:
  omnibus:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '${GITLAB_DOMAIN}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_DOMAIN}'
    ports:
      - 2222:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    deploy:
      labels:
        traefik.backend: omnibus
        traefik.frontend.rule: "Host:${GITLAB_DOMAIN}"
      placement:
        constraints:
          - node.role == manager
 
  runner:
    image: 'gitlab/gitlab-runner:v1.11.4'
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config: