version: '3'

services:
  omnibus:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'lab.freelyformd.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://lab.freelyformd.com'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        registry_external_url 'https://registry.freelyformd.com'
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.zoho.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = 'login'
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_user_name'] = 'lab@freelyformd.com'
        gitlab_rails['smtp_password'] = 'freelyformd%%'
        gitlab_rails['smtp_domain'] = 'smtp.zoho.com'
        gitlab_rails['gitlab_email_from'] = 'lab@freelyformd.com'
        gitlab_rails['gitlab_email_reply_to'] = 'lab@freelyformd.com'
    ports:
      - 2222:22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - default
      - proxy
    deploy:
      labels:
        traefik.enable: "port"
        traefik.frontend.rule: 'Host: lab.freelyformd.com, registry.freelyformd.com'
        traefik.port: 80
        traefik.docker.network: 'proxy'
      placement:
        constraints:
          - node.role == manager
 
  runner:
    image: 'gitlab/gitlab-runner:v1.11.4'
    networks:
      - default
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 3

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

networks:
  default:
  proxy:
    external: true