version: '3'

services:
  traefik:
    image: traefik:alpine
    command: --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443' --defaultentrypoints="http,https" --acme --acme.email=freelyformd@gmail.com --acme.storage=acme.json --acme.onhostrule --docker --docker.swarmmode --docker.domain=freelyformd.com --docker.watch --web
    ports:
      - 80:80
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: 'Host: proxy.freelyformd.com'
        traefik.port: 8080
      placement:
        constraints:
          - node.role == manager

networks:
  traefik-net:
    external: true
