version: '3'

services:
  web:
    image: 'portainer/portainer'
    networks:
      - proxy
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      labels:
        traefik.enable: "true"
        traefik.frontend.rule: 'Host: portainer.freelyformd.com'
        traefik.port: 9000
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true

volumes:
  portainer_data:
